[[permission]]
identifier = "allow-authenticate-passkey"
description = "Enables the authenticate_passkey command without any pre-configured scope."
commands.allow = ["authenticate_passkey"]

[[permission]]
identifier = "deny-authenticate-passkey"
description = "Denies the authenticate_passkey command without any pre-configured scope."
commands.deny = ["authenticate_passkey"]